volumes:
  db_storage:
  n8n_data:


networks:
  default:
    name: n8n-stack-network
    external: true

services:
  n8n-db:
    image: postgres:16
    container_name: n8n-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"

    #deploy:
    #  resources:
    #    limits:
    #      cpus: '2'
    #      memory: 1024M
    stop_grace_period: 60s

    env_file:
      - .env

    environment:
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}

    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files # Uncomment if you want to mount local folders
      - ./backup:/backup # Uncomment if you want to mount local folders

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:5678/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    depends_on:
      n8n-db:
        condition: service_healthy
